import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

/* Components */
import Contact from "../components/contact/Contact";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contact />
    </div>
  );
};

export default Home;
